### ISSUE TITLE
Observable<Bool> startWith(true) is not working

### ISSUE THREAD

**Issue by zinwalin** [faresbh/rx_laptimer#1]
let isRunning = Observable
            .merge([btnPlay.rx.tap.map({ return true }), btnStop.rx.tap.map({ return false })])
            .startWith(true)
            .share()

I try to start timer once app launch, so I set startWith(true) for Observable isRunning, but timer doesn't start immediately. 

How can I fix it ?

**Comment by faresbh** [comment]
In this project, isRunning is coupled with the tap on the play button. 
if you want to perform a timer on app start then you can do that by making a button click like so :
`btnPlay.sendActions(for: .touchUpInside) 
`
This will fire the timer automatically.
